apiVersion: v1
kind: Secret
metadata:
  name: volume-secret
  namespace: default
stringData:
  iops: "<IOPS_value>" # Enter the IOPS as per the profile that you want to allow for your Block Storage instance. It must match the Block Storage for VPC tier that you plan to use.
  zone: "<zone>" # Enter the VPC zone where you want to create the Block Storage instance. Make sure that you use a zone that your worker nodes are connected to.
  tags: "<tags>" # Enter a comma-separated list of tags to use when the PVC is created. Tags can help you find your storage instance more easily after it is created.
  encrypted: "<true_or_false>" # Enter true to create a secret that sets up encryption for Block Storage volumes. If set to true, you need to provider encryption key as well.
  resourceGroup: "<resource_group>" # Enter the resource group that you want your Block Storage instance to get access to. By default gets the resource group of your cluster.
  encryptionKey: "<encryption_key>" # If you entered true for encrypted stringData, then enter the root key CRN of your Key Protect service instance that you want to use to encrypt your Block Storage volumes.
type: vpc.block.csi.ibm.io
