kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ibm-vpc-block-csi-controller
spec:
  template:
    spec:
      containers:
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.2.1
        - name: csi-attacher
          image:  registry.k8s.io/sig-storage/csi-attacher:v3.5.0
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.6.0
        - name: iks-vpc-block-driver
          imagePullPolicy: Always
          image: icr.io/acadia-images/ibm-vpc-block-csi-driver:amd64-sdp-beta
        - name: csi-resizer
          image: registry.k8s.io/sig-storage/csi-resizer:v1.5.0
        - name: csi-snapshotter
          image: registry.k8s.io/sig-storage/csi-snapshotter:v6.0.1
