kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: ibm-vpc-block-csi-node
spec:
  template:
    spec:
      containers:
        - name: iks-vpc-block-node-driver
          imagePullPolicy: Always
          image: icr.io/acadia-images/ibm-vpc-block-csi-driver:amd64-sdp-beta
        - name: csi-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.0
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.6.0
